secrets:
  bitflyer:
    api_key:
    api_secret:

trade:
  invest_money: 10000
  cut_loss: 57000
  safe_money: 40000

dry_run:
  bitflyer:
    XRP_JPY: true
    FX_BTC_JPY: true

connection_string: tradebot:{password}@tcp(127.0.0.1:3306)/gotradecrypto?charset=utf8mb4&parseTime=True&loc=Local
